fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: oauth_authorize
  user_class: App\Entity\User
  from_email:
    address: "tuanquynh0508@gmail.com"
    sender_name: "Nguyen Nhu Tuan"