fos_oauth_server:
  db_driver: orm
  client_class:        App\Entity\OAuth2\Client
  access_token_class:  App\Entity\OAuth2\AccessToken
  refresh_token_class: App\Entity\OAuth2\RefreshToken
  auth_code_class:     App\Entity\OAuth2\AuthCode
  service:
    user_provider: platform.user.provider
    options:
      supported_scopes: user
      access_token_lifetime: 86400
      refresh_token_lifetime: 1209600
      auth_code_lifetime: 30
  template:
    engine: twig