#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

acme_oauth_server_auth_login:
  path:  /oauth/v2/auth_login
  controller: App\Controller\SecurityController::login

acme_oauth_server_auth_login_check:
  path:  /oauth/v2/auth_login_check
  controller: App\Controller\SecurityController::loginCheck